#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'superDigit' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING n
#  2. INTEGER k
#

def superDigit(n, k):
    # Write your code here
    if len(n) == 1:
        return int(n)
    lst = list(map(int,n))
    summ = sum(lst) * k
    k = 1
    summ = str(summ)
    return superDigit(summ , k)

if __name__ == '__main__':
